on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Tag to be applied, for example 1.0.0
      changelog:
        required: true
        type: string
      commit:
        type: string
        description: full commit hash, if none supplied, latest main is taken

env:
  ASSETS_PATH: ./Assets
  RELEASE_PATH: Packages 
  ARTIFACT_DURATION: 30 # In days
  UPLOAD_ENDPOINT: https://api.vrlabs.dev/packages/add
  WORKFLOW_VERSION: 1.0.1

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Determine input
        run: |
          if [[ -z "${{ github.event.inputs.user_input }}" ]]; then
            echo "checkout_ref=main" >> $GITHUB_ENV
          else
            echo "checkout_ref=${{ github.event.inputs.user_input }}" >> $GITHUB_ENV
          fi
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.checkout_ref }}
          path: ${{ env.ASSETS_PATH }}
      - name: Create tag
        run: |
          cd ${{ env.ASSETS_PATH }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ inputs.tag }}" "${{ env.checkout_ref }}"
          git push origin "${{ inputs.tag }}"
          cd -
      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: TestSMIMEJelle/Repositories
          path: ./Actions
      - name: Run action
        uses: ./Actions/VRC-Asset-Release-And-Upload.yml
        working-directory: ${{ env.ASSETS_PATH }}
        with:
          ASSETS_PATH: ${{ . }}
          RELEASE_PATH: ${{ env.RELEASE_PATH }}
          UPLOAD_ENDPOINT: ${{ env.UPLOAD_ENDPOINT }}
          TAG:
            required: true
            type: string
          ARTIFACT_DURATION:
            required: true
            type: int
