on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        type: string
        description: Tag to be applied, for example 1.0.0
      CHANGELOG:
        required: true
        type: string
      COMMIT:
        type: string
        description: full commit hash, if none supplied, latest main is taken

env:
  ASSETS_PATH: ./Assets
  RELEASE_PATH: Packages 
  ARTIFACT_DURATION: 30 # In days
  UPLOAD_ENDPOINT: https://api.vrlabs.dev/packages/add
  WORKFLOW_VERSION: 1.0.1

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions: 
      contents: write
      workflow: write
    steps:
      - name: Determine input
        run: |
          if [[ -z "${{ inputs.COMMIT }}" ]]; then
            echo "CHECKOUT_REF=main" >> $GITHUB_ENV
          else
            echo "CHECKOUT_REF=${{ inputs.COMMIT }}" >> $GITHUB_ENV
          fi
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}
          path: ${{ env.ASSETS_PATH }}
      - name: Create tag

        run: |
          cd ${{ env.ASSETS_PATH }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ inputs.TAG }}" "${{ env.CHECKOUT_REF }}"
          git push origin "${{ inputs.TAG }}"
          cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: TestSMIMEJelle/Repositories
          path: ./Actions
      - name: Run action
        uses: ./Actions
        with:
          ASSETS_PATH: ${{ env.ASSETS_PATH }}
          RELEASE_PATH: ${{ env.RELEASE_PATH }}
          UPLOAD_ENDPOINT: ${{ env.UPLOAD_ENDPOINT }}
          TAG: ${{ inputs.TAG }}
          ARTIFACT_DURATION: ${{ env.ARTIFACT_DURATION }}
          CHANGELOG: ${{ inputs.CHANGELOG }}
